"""add_reset_password_otp_columns

Revision ID: 315c924ffeb4
Revises: b915c7f12c63
Create Date: 2026-07-07 10:42:32.765500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315c924ffeb4'
down_revision: Union[str, Sequence[str], None] = 'b915c7f12c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_password_otp')
    # ### end Alembic commands ###
